version: '3'

includes:
  cluster: ../../lib-cluster-manager/.taskfiles/k3d.yaml
  gocd: 
    taskfile: ../../lib-cluster-manager/.taskfiles/apps/gocd.yaml
    dir: ../../lib-cluster-manager
    
vars:
  CLUSTER_NAME: 
    sh: basename "$PWD"

tasks:
  configure:
    - task: gocd:install:helm
    - task: gocd:install:ingressroute
 
  create:
    cmds:
    - task: cluster:create
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'
    - task: cluster:wait-for-traefik
    - task: configure 


  delete:
    cmds:
    - task: cluster:delete
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'

  start:
    cmds:
    - task: cluster:start
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'

  stop:
    cmds:
    - task: cluster:stop
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'