version: '3'

includes:
  cluster: 
    taskfile: ../../lib-cluster-manager/system-tools/k3d/Taskfile.yaml
  teleport: 
    taskfile: ../../lib-cluster-manager/k8s-apps/teleport/Taskfile.yaml
    dir: ../../lib-cluster-manager/k8s-apps/teleport
    
vars:
  CLUSTER_NAME: 
    sh: basename "$PWD"

tasks:
  configure:
    - task: teleport:update:traefik:helm
    - task: teleport:install:helm
    - task: teleport:install:ingress-routes
    - task: teleport:add-user
 
  create:
    cmds:
    - task: cluster:create
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'
    - task: configure 

  delete:
    cmds:
    - task: cluster:delete
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'

  start:
    cmds:
    - task: cluster:start
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'

  stop:
    cmds:
    - task: cluster:stop
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'