version: '3'

includes:
  git: lib-system-manager/.taskfiles/git.yaml

tasks:
  default:
    cmds:
    - task -l
    silent: true

  commit:
  - cd lib-system-manager && task git:commit:fast
  - cd lib-cluster-manager && task git:commit:fast
  - task: git:commit:fast
