version: 3

includes:
  grafana-cloud:
    taskfile: ./taskfiles/grafana-cloud.yaml
  robusta: ./taskfiles/robusta.yaml
  cert-manager: 
    taskfile: ./modules/cert-manager/Taskfile.yaml
    dir: ./modules/cert-manager
  ghost:
    taskfile: ../../../lib-cluster-manager/k8s-apps/ghost/Taskfile.yaml
    dir: ../../../lib-cluster-manager/k8s-apps/ghost
  openebs: 
    taskfile: ../../../lib-cluster-manager/k8s-storage/openebs/Taskfile.yaml
    dir: ../../../lib-cluster-manager/k8s-storage/openebs
  k3sup:
    taskfile: ../../../lib-cluster-manager/cluster-installer/k3sup/Taskfile.yaml
  traefik: 
    taskfile: ./modules/traefik/Taskfile.yaml
    dir: ./modules/traefik
  wg-easy: 
    taskfile: ./modules/wg-easy/Taskfile.yaml
    dir: ./modules/wg-easy

    
vars:
  CLUSTER_NAME: 
    sh: basename "$PWD"

tasks:
  configure:
    cmds:
    - task: openebs:install:helm
    - task: cert-manager:install:helm
    - task: cert-manager:create:acme-cluster-issuer
      vars:
        EMAIL: krzwiatrzyk@protonmail.com
        INGRESS_CLASS: traefik
    - task: cert-manager:create:certificate
      vars:
        DOMAIN: krzwiatrzyk.pl
    - task: traefik:create:tlsstore
      vars:
        DOMAIN: krzwiatrzyk.pl
    - task: ghost:install:custom-chart
    - task: traefik:update
    - task: traefik:install:ingress-route
    - task: wg-easy:install
  
  install:cluster:
    cmds:
    - task: k3sup:install:cluster
      vars:
        IP: 91.228.198.230
        USER: root
        NAME: krzwiatrzyk
        K3S_EXTRA_ARGS: '--no-deploy local-storage'


  # ----------- EXTRAS -------------

  install:kubestr:
  - wget -nc https://github.com/kastenhq/kubestr/releases/download/v0.4.31/kubestr_0.4.31_Linux_amd64.tar.gz
  - mkdir -p kubestr
  - tar zxvf kubestr_0.4.31_Linux_amd64.tar.gz --directory=kubestr
  - chmod +x kubestr/kubestr
  - sudo mv kubestr/kubestr /usr/local/bin/kubestr
  - rm -rf kubestr

  validate-storage-options:
  - kubestr

  kasten:install:

  kasten:install:helm:add-repo:
    cmds:
    - helm repo add kasten https://charts.kasten.io/
    status:
    - helm repo list | grep kasten

  kasten:install:helm:
    deps:
    - kasten:install:helm:add-repo
    cmds:
    - helm upgrade --install k10 kasten/k10 --namespace=kasten-io --create-namespace

  helm-secrets:install:
    cmds:
    - helm plugin install https://github.com/jkroepke/helm-secrets --version v3.14.0 | true
    - helm plugin update secrets
    status:
    - helm plugin list | grep secrets | grep 3.14

