version: 3

includes:
  cluster: 
    taskfile: ../../lib-cluster-manager/system-tools/k3d/Taskfile.yaml
  cert-manager: 
    taskfile: ../../lib-cluster-manager/k8s-apps/cert-manager/Taskfile.yaml
    dir: ../../lib-cluster-manager/k8s-apps/cert-manager
  ghost:
    taskfile: ../../lib-cluster-manager/k8s-apps/ghost/Taskfile.yaml
    dir: ../../lib-cluster-manager/k8s-apps/ghost
  openebs: 
    taskfile: ../../lib-cluster-manager/k8s-storage/openebs/Taskfile.yaml
    dir: ../../lib-cluster-manager/k8s-storage/openebs
  k3sup:
    taskfile: ../../lib-cluster-manager/cluster-installer/k3sup/Taskfile.yaml
  traefik: 
    taskfile: ../../lib-cluster-manager/k8s-networking/traefik/Taskfile.yaml
    dir: ../../lib-cluster-manager/k8s-networking/traefik

    
vars:
  CLUSTER_NAME: 
    sh: basename "$PWD"

tasks:
  configure:
    cmds:
    - task: openebs:install:helm
    - task: cert-manager:install:helm
    - task: cert-manager:create:acme-cluster-issuer
      vars:
        EMAIL: krzwiatrzyk@protonmail.com
        INGRESS_CLASS: traefik
    - task: cert-manager:create:certificate
      vars:
        DOMAIN: krzwiatrzyk.pl
    - task: traefik:create:tlsstore
      vars:
        DOMAIN: krzwiatrzyk.pl
  
  install:cluster:
    cmds:
    - task: k3sup:install:cluster
      vars:
        IP: 91.228.198.230
        USER: root
        NAME: krzwiatrzyk
        K3S_EXTRA_ARGS: '--no-deploy local-storage'

  install:ghost:
  - task: ghost:install:custom-chart
    # vars:
    #   VALUES_FILE:
    #     sh: echo $(pwd)/values/ghost-values.yaml


  grafana-cloud:install:agent:config-map:
  - sops -d manifests/grafana-cloud-agent-configmap.yaml | kubectl apply -f - -n grafana-cloud
  - sops -d manifests/grafana-cloud-agent-logs-configmap.yaml | kubectl apply -f - -n grafana-cloud

  grafana-cloud:install:agent:statefulset:
    env:
      MANIFEST_URL: https://raw.githubusercontent.com/grafana/agent/v0.24.0/production/kubernetes/agent-bare.yaml
      NAMESPACE: grafana-cloud
    cmds:
    - /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/grafana/agent/v0.24.0/production/kubernetes/install-bare.sh)" | kubectl apply -f -


  grafana-cloud:install:agent:daemonset:
    env:
      MANIFEST_URL: https://raw.githubusercontent.com/grafana/agent/v0.24.0/production/kubernetes/agent-loki.yaml
      NAMESPACE: grafana-cloud
    cmds:
    - /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/grafana/agent/v0.24.0/production/kubernetes/install-bare.sh)" | kubectl apply -f -
 

  grafana-cloud:install:kube-state-metrics:
  - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  - >
    helm install kube-state-metrics prometheus-community/kube-state-metrics 
    --set image.tag=v2.4.2 
    -n grafana-cloud

  grafana-cloud:create-namespace:
    cmds:
    - kubectl create namespace grafana-cloud
    status:
    - kubectl assert exist namespace grafana-cloud

  grafana-cloud:install:
    cmds:
    - task: grafana-cloud:create-namespace
    - task: grafana-cloud:install:kube-state-metrics
    - task: grafana-cloud:install:agent:config-map
    - task: grafana-cloud:install:agent:statefulset
    - task: grafana-cloud:install:agent:daemonset