apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgresql
  namespace: doctor
spec:
  entryPoints:
    - postgresql
  routes:
  - match: HostSNI(`*`)
    services:   
    - name: postgresql
      port: 5432