version: '3'

includes:
  cluster: 
    taskfile: ../../lib-cluster-manager/.taskfiles/k3d.yaml
  knative: 
    taskfile: ../../lib-cluster-manager/k8s-apps/knative/Taskfile.yaml
    dir: ../../lib-cluster-manager/k8s-apps/knative
    
vars:
  CLUSTER_NAME: 
    sh: basename "$PWD"

tasks:
  configure:
    - task: knative:install:operator
    - task: knative:install:serving
    - task: knative:demo:service:hello
 
  create:
    cmds:
    - task: cluster:create
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'
    - task: configure 


  delete:
    cmds:
    - task: cluster:delete
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'

  start:
    cmds:
    - task: cluster:start
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'

  stop:
    cmds:
    - task: cluster:stop
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'