version: '3'

# KubeVela UI
# login: admin
# password: VelaUX12345


includes:
  cluster: 
    taskfile: ./.taskfiles/k3d.yaml
  kubevela: ./.taskfiles/kubevela.yaml

vars:
  CLUSTER_NAME: 
    sh: basename "$PWD"

tasks:
  configure:
  - task: kubevela:install
  - task: kubevela:install:ui
 
  create:
    cmds:
    - task: cluster:create
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'
    - task: cluster:wait-for-traefik
    - task: configure 


  delete:
    cmds:
    - task: cluster:delete
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'

  start:
    cmds:
    - task: cluster:start
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'

  stop:
    cmds:
    - task: cluster:stop
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'