version: '3'

includes:
  cluster: 
    taskfile: ../../lib-cluster-manager/.taskfiles/k3d.yaml
  threat-mapper: 
    taskfile: ../../lib-cluster-manager/k8s-apps/threat-mapper/Taskfile.yaml
    dir: ../../lib-cluster-manager/k8s-apps/threat-mapper
  openebs: 
    taskfile: ../../lib-cluster-manager/k8s-storage/openebs/Taskfile.yaml
    dir: ../../lib-cluster-manager/k8s-storage/openebs
    
vars:
  CLUSTER_NAME: 
    sh: basename "$PWD"

tasks:
  configure:
    - task: openebs:install:helm
    - task: threat-mapper:install:helm
    - task: threat-mapper:install:ingress-route
 
  create:
    cmds:
    - task: cluster:create
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'
    - task: cluster:wait-for-traefik
    - task: configure 


  delete:
    cmds:
    - task: cluster:delete
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'

  start:
    cmds:
    - task: cluster:start
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'

  stop:
    cmds:
    - task: cluster:stop
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'