apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argus
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: https://krzwiatrzyk.github.io/charts/
    targetRevision: '0.0.x'
    chart: argus
    helm:
      values: |
        ingress:
          main:
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
            enabled: true
            hosts:
              - host: argus.vcap.me
                paths:
                  - path: /
                    pathType: Prefix
        podSecurityContext:
          runAsUser: 65534
          runAsGroup: 65534
          fsGroup: 65534
        securityContext:
          readOnlyRootFilesystem: false
        persistence:
          config:
            objectName: argus-config
            mountPath: /config
        command:
        - "/bin/sh"
        - "-c"
        - "cp /config/config.yml /etc/argus/config.yml && /bin/argus -config.file=/etc/argus/config.yml"

        config:
          service:
            minio:
              semantic_versioning: false
              regex_version: (.*)
              type: github
              url: minio/minio
              web_url: https://github.com/minio/minio/releases/{{ version }}
              icon: https://raw.githubusercontent.com/minio/minio/master/.github/logo.svg?sanitize=true
              status:  
                current_version: RELEASE.2020-08-08T02-33-58Z
                current_version_timestamp: 2022-05-30T07:51:53Z
        
  destination:
    server: https://kubernetes.default.svc
    namespace: argus
  syncPolicy:
    syncOptions:
    - CreateNamespace=true