apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: clusters/firefly/manifests/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
