
apiVersion: k3d.io/v1alpha4
kind: Simple
servers: 1 
agents: 0 
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
# volumes:
#   - volume: /k3d/gocd:/k3d/gocd
#     nodeFilters:
#     - server:0