apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tellery.krzwiatrzyk.pl
  namespace: doctor
spec:
  secretName: tellery.krzwiatrzyk.pl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: tellery.krzwiatrzyk.pl
  dnsNames:
  - tellery.krzwiatrzyk.pl