version: '3'

includes:
  cluster: 
    taskfile: ../../lib-cluster-manager/system-tools/k3d/Taskfile.yaml
  rancher: 
    taskfile: ../../lib-cluster-manager/k8s-multicluster/rancher/Taskfile.yaml
    dir: ../../lib-cluster-manager/k8s-multicluster/rancher
    
vars:
  CLUSTER_NAME: 
    sh: basename "$PWD"

tasks:
  configure:
    - task: rancher:install:helm
    - task: rancher:show:bootstrap:url
 
  create:
    cmds:
    - task: cluster:create
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'
    - task: configure 

  delete:
    cmds:
    - task: cluster:delete
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'

  start:
    cmds:
    - task: cluster:start
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'

  stop:
    cmds:
    - task: cluster:stop
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'