apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-firefly
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:                      
  - kind: Rule
    match: Host(`argocd.{{ .Values.hostIP }}.nip.io`)   
    services:                  
    - name: argocd-server              
      port: 80                