
apiVersion: k3d.io/v1alpha4
kind: Simple
servers: 1 
agents: 0 
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 3023:3023
    nodeFilters:
      - server:0
  - port: 3024:3024
    nodeFilters:
      - server:0
  - port: 3026:3026
    nodeFilters:
      - server:0
  - port: 3036:3036
    nodeFilters:
      - server:0
