version: '3'

includes:
  cluster: 
    taskfile: ../../lib-cluster-manager/system-tools/k3d/Taskfile.yaml
  kube-prometheus-stack: 
    taskfile: ../../lib-cluster-manager/k8s-monitoring/kube-prometheus-stack/Taskfile.yaml
    dir: ../../lib-cluster-manager/k8s-monitoring/kube-prometheus-stack
  traefik:
    taskfile: ../../lib-cluster-manager/k8s-networking/traefik/Taskfile.yaml
    dir: ../../lib-cluster-manager/k8s-networking/traefik
  stackgres:
    taskfile: ../../lib-cluster-manager/k8s-databases/stackgres/Taskfile.yaml
    dir: ../../lib-cluster-manager/k8s-databases/stackgres
    
vars:
  CLUSTER_NAME: 
    sh: basename "$PWD"

tasks:
  configure:
    - task: kube-prometheus-stack:install:helm
    - task: kube-prometheus-stack:install:prometheus:ingress-route
    - task: kube-prometheus-stack:install:grafana:ingress-route
    - task: traefik:install:ingress-route
    - task: stackgres:install:helm
 
  create:
    cmds:
    - task: cluster:create
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'
    - task: configure 

  delete:
    cmds:
    - task: cluster:delete
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'

  start:
    cmds:
    - task: cluster:start
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'

  stop:
    cmds:
    - task: cluster:stop
      vars:
        CLUSTER_NAME: '{{ .CLUSTER_NAME }}'