apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: notification
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Notifications
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  destinations:
  - namespace: notification
    server: https://kubernetes.default.svc

